# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hack_challenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hack_challenge

  pod 'lottie-ios'
  pod 'Alamofire'
  pod 'SnapKit'

end
